[2024-04-10T20:00:47.060+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_congress_data.get_votes_from_downloaded_bills manual__2024-04-10T19:57:53.334319+00:00 [queued]>
[2024-04-10T20:00:47.069+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_congress_data.get_votes_from_downloaded_bills manual__2024-04-10T19:57:53.334319+00:00 [queued]>
[2024-04-10T20:00:47.070+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-10T20:00:47.083+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_votes_from_downloaded_bills> on 2024-04-10 19:57:53.334319+00:00
[2024-04-10T20:00:47.091+0000] {standard_task_runner.py:60} INFO - Started process 1229 to run task
[2024-04-10T20:00:47.112+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_congress_data', 'get_votes_from_downloaded_bills', 'manual__2024-04-10T19:57:53.334319+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/upload_congress_data.py', '--cfg-path', '/tmp/tmp8t2rl51r']
[2024-04-10T20:00:47.120+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask get_votes_from_downloaded_bills
[2024-04-10T20:00:47.175+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_congress_data.get_votes_from_downloaded_bills manual__2024-04-10T19:57:53.334319+00:00 [running]> on host 3ad97e665188
[2024-04-10T20:00:47.265+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_congress_data' AIRFLOW_CTX_TASK_ID='get_votes_from_downloaded_bills' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T19:57:53.334319+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-10T19:57:53.334319+00:00'
[2024-04-10T20:00:53.986+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:00:54.140+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:00:54.292+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:00:54.440+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:00:59.265+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:00:59.553+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:02.612+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:02.778+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:02.926+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:03.086+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:04.533+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:04.690+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:04.881+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:05.030+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:05.513+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:05.675+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:05.836+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:05.997+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T20:01:09.699+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 125, in get_votes_for_saved_bills
    get_votes(bill_json=local_file_path, save_folder=save_folder)
  File "/opt/airflow/dags/scripts/python/get_data.py", line 133, in get_votes
    bill_number = bill['bill']['number']
                  ~~~~^^^^^^^^
KeyError: 'bill'
[2024-04-10T20:01:09.715+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_congress_data, task_id=get_votes_from_downloaded_bills, execution_date=20240410T195753, start_date=20240410T200047, end_date=20240410T200109
[2024-04-10T20:01:09.729+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task get_votes_from_downloaded_bills ('bill'; 1229)
[2024-04-10T20:01:09.791+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-10T20:01:09.811+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
