[2024-03-26T03:28:52.593+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.bills_external_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-26T03:28:52.607+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.bills_external_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-26T03:28:52.609+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-26T03:28:52.623+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bills_external_table_task> on 2024-03-15 00:00:00+00:00
[2024-03-26T03:28:52.631+0000] {standard_task_runner.py:60} INFO - Started process 132 to run task
[2024-03-26T03:28:52.637+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'bills_external_table_task', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpdunc8aef']
[2024-03-26T03:28:52.642+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask bills_external_table_task
[2024-03-26T03:28:52.703+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.bills_external_table_task scheduled__2024-03-15T00:00:00+00:00 [running]> on host cb295ecee912
[2024-03-26T03:28:52.764+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='bills_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-03-26T03:28:52.769+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-26T03:28:52.772+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-26T03:28:52.774+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-26T03:28:53.927+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=upload_historical_congress_data, task_id=bills_external_table_task, execution_date=20240315T000000, start_date=20240326T032852, end_date=20240326T032853
[2024-03-26T03:28:53.982+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T03:28:53.999+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-28T03:25:35.078+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.bills_external_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-28T03:25:35.086+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.bills_external_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-28T03:25:35.088+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-28T03:25:35.098+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bills_external_table_task> on 2024-03-15 00:00:00+00:00
[2024-03-28T03:25:35.108+0000] {standard_task_runner.py:60} INFO - Started process 185 to run task
[2024-03-28T03:25:35.116+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'bills_external_table_task', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmp8n6w8jhd']
[2024-03-28T03:25:35.123+0000] {standard_task_runner.py:88} INFO - Job 149: Subtask bills_external_table_task
[2024-03-28T03:25:35.180+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.bills_external_table_task scheduled__2024-03-15T00:00:00+00:00 [running]> on host be5d54f7fe24
[2024-03-28T03:25:35.304+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='bills_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-03-28T03:25:35.308+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-28T03:25:35.309+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-28T03:25:35.310+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-28T03:25:35.908+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1783, in execute
    table = bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 422, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 797, in create_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/inbound-ship-412204/datasets/Congress/tables?prettyPrint=false: Invalid value for type: STRUCT<ACTIONDATE DATE, TEXT STRING> is not a valid value
[2024-03-28T03:25:35.920+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=bills_external_table_task, execution_date=20240315T000000, start_date=20240328T032535, end_date=20240328T032535
[2024-03-28T03:25:35.931+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 149 for task bills_external_table_task (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/inbound-ship-412204/datasets/Congress/tables?prettyPrint=false: Invalid value for type: STRUCT<ACTIONDATE DATE, TEXT STRING> is not a valid value; 185)
[2024-03-28T03:25:35.953+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T03:25:35.984+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
