[2024-04-10T19:44:10.675+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_congress_data.get_votes_from_downloaded_bills manual__2024-04-10T19:40:33.743512+00:00 [queued]>
[2024-04-10T19:44:10.683+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_congress_data.get_votes_from_downloaded_bills manual__2024-04-10T19:40:33.743512+00:00 [queued]>
[2024-04-10T19:44:10.683+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-10T19:44:10.692+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_votes_from_downloaded_bills> on 2024-04-10 19:40:33.743512+00:00
[2024-04-10T19:44:10.700+0000] {standard_task_runner.py:60} INFO - Started process 927 to run task
[2024-04-10T19:44:10.705+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_congress_data', 'get_votes_from_downloaded_bills', 'manual__2024-04-10T19:40:33.743512+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/upload_congress_data.py', '--cfg-path', '/tmp/tmpk95o7t9r']
[2024-04-10T19:44:10.709+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask get_votes_from_downloaded_bills
[2024-04-10T19:44:10.766+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_congress_data.get_votes_from_downloaded_bills manual__2024-04-10T19:40:33.743512+00:00 [running]> on host 3ad97e665188
[2024-04-10T19:44:10.872+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_congress_data' AIRFLOW_CTX_TASK_ID='get_votes_from_downloaded_bills' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T19:40:33.743512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-10T19:40:33.743512+00:00'
[2024-04-10T19:44:17.737+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:17.886+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:18.051+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:18.231+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:22.968+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:23.118+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:24.696+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:24.859+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:25.021+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:25.179+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:26.538+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:26.686+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:26.833+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:26.969+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:27.538+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:27.698+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:27.846+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:28.040+0000] {logging_mixin.py:188} INFO - An exception occurred 'rollcall-vote' Failed to save one or more votes for {bill_type} {bill_number}
[2024-04-10T19:44:31.274+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/python/get_data.py", line 125, in get_votes_for_saved_bills
    get_votes(bill_json=local_file_path, save_folder=save_folder)
  File "/opt/airflow/dags/scripts/python/get_data.py", line 133, in get_votes
    bill_number = bill['bill']['number']
                  ~~~~^^^^^^^^
KeyError: 'bill'
[2024-04-10T19:44:31.302+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_congress_data, task_id=get_votes_from_downloaded_bills, execution_date=20240410T194033, start_date=20240410T194410, end_date=20240410T194431
[2024-04-10T19:44:31.327+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task get_votes_from_downloaded_bills ('bill'; 927)
[2024-04-10T19:44:31.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-10T19:44:31.409+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
